version: '2'
services:
  web:
#    #image: php:8.0-apache
    build: ./php
    ports:
      - 80:80
    volumes_from:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./db:/var/lib/mysql
      - ./src:/var/www/html
      - ./mysql_conf:/etc/mysql
#  phpmyadmin:
#    image: phpmyadmin
#    ports:
#      - 8080:80
  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211
