FROM php:8.0-apache

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions gd mysqli pdo_mysql mcrypt

RUN a2enmod rewrite

COPY ./php.ini /usr/local/etc/php/conf.d/php.ini
